In [49]:
import pandas as pd

filename = "./filtered/1875_filtered.xlsx"
df = pd.read_excel(filename)

## print the first 5 rows of the data
df.head()

,Unnamed: 0,nom_rue,nom_rue_htr_corr,nom_rue_norm,no_maison,proprietaire_nom,proprietaire_nom_corr,proprietaire_nom_htr_corr,proprietaire_nom_norm,chef_prenom,...,pensionnaires_origine_corr,pensionnaires_origine_htr_corr,pensionnaires_origine_norm,pensionnaires_condition,pensionnaires_condition_top_terms,pensionnaires_condition_htr_corr,pensionnaires_condition_norm,pensionnaires_recepisse,observations,Page
0,1,grand st jean,grand st jean,grand st jean,1,augy,augy,augy,augy,vve de rodolph,...,rougemont|epalinges,rougemont|epalinges,rougemont|epalinges,domestique|tailleuse,domestique|tailleuse,domestique|tailleuse,domestique|tailleuse,8487,·,1
1,2,grand st jean,grand st jean,grand st jean,·,·,·,·,·,vve de bean,...,gd duchi de b|neuchatel,gd duchi de b|neuchatel,gd duchi de b|neuchatel,henuisier|emp lad c que,menuisier|emp lad c que,menuisier|emp lad c que,menuisier|emp lad c que,15090,chez lui,1
2,3,grand st jean,grand st jean,grand st jean,2,kohler,kohler,kohler,kohler,vve d amedee,...,begnins,begnins,begnins,dque,dque,dque,domestique,12816,·,1
3,4,grand st jean,grand st jean,grand st jean,·,·,·,·,·,charles ba theleny,...,·,·,·,·,·,·,·,·,·,1
4,5,grand st jean,grand st jean,grand st jean,·,·,·,·,·,charles,...,peney le jorat|koppaz|cally|savoie,peney le jorat|koppaz|cally|savoie,peney le jorat|koppaz|cally|savoie,dque|dque|dque|dque,dque|dque|dque|dque,dque|dque|dque|dque,domestique|domestique|domestique|domestique,18773|·|·|22234,·,1

In [50]:
## filter the data to only include the rows where the value of the column "pensionnaires_condition" is not empty or NaN or "."
df_condition = df[df["pensionnaires_condition"].notnull() & (df["pensionnaires_condition"] != "·")]

## print the first 5 rows of the filtered data
df_condition.head()

,Unnamed: 0,nom_rue,nom_rue_htr_corr,nom_rue_norm,no_maison,proprietaire_nom,proprietaire_nom_corr,proprietaire_nom_htr_corr,proprietaire_nom_norm,chef_prenom,...,pensionnaires_origine_corr,pensionnaires_origine_htr_corr,pensionnaires_origine_norm,pensionnaires_condition,pensionnaires_condition_top_terms,pensionnaires_condition_htr_corr,pensionnaires_condition_norm,pensionnaires_recepisse,observations,Page
0,1,grand st jean,grand st jean,grand st jean,1,augy,augy,augy,augy,vve de rodolph,...,rougemont|epalinges,rougemont|epalinges,rougemont|epalinges,domestique|tailleuse,domestique|tailleuse,domestique|tailleuse,domestique|tailleuse,8487,·,1
1,2,grand st jean,grand st jean,grand st jean,·,·,·,·,·,vve de bean,...,gd duchi de b|neuchatel,gd duchi de b|neuchatel,gd duchi de b|neuchatel,henuisier|emp lad c que,menuisier|emp lad c que,menuisier|emp lad c que,menuisier|emp lad c que,15090,chez lui,1
2,3,grand st jean,grand st jean,grand st jean,2,kohler,kohler,kohler,kohler,vve d amedee,...,begnins,begnins,begnins,dque,dque,dque,domestique,12816,·,1
4,5,grand st jean,grand st jean,grand st jean,·,·,·,·,·,charles,...,peney le jorat|koppaz|cally|savoie,peney le jorat|koppaz|cally|savoie,peney le jorat|koppaz|cally|savoie,dque|dque|dque|dque,dque|dque|dque|dque,dque|dque|dque|dque,domestique|domestique|domestique|domestique,18773|·|·|22234,·,1
5,6,grand st jean,grand st jean,grand st jean,·,·,·,·,·,adolphe,...,ollons,ollons,ollons,dque,dque,dque,domestique,·,·,1

In [51]:
## filter the rows where the value of the column "pensionnaires_condition" contains "pension" or "pensre"
df_pensionnaires = df_condition[df_condition["pensionnaires_condition"].str.contains("pension|pensre", na=False)] 

## print the first 5 rows of the filtered data
df_pensionnaires.head()

## print the number of rows in the filtered data
df_pensionnaires.shape

(413, 54)

In [52]:
## print the values of the column "chef_vocation" of the filtered data
df_pensionnaires["chef_vocation"]

978        rentiere
982         turiere
987        rentiere
991     vique|taire
998        veu idem
           ...
6627     couturiere
6633        fermier
6639       vigneron
6640      jardinier
6649        laitier
Name: chef_vocation, Length: 413, dtype: object

In [53]:
## print the values of the column "pensionnaires_origine" of the filtered data
df_pensionnaires["pensionnaires_origine"]

978                           yverdon|chapelles|neuchatel
982                           auborne|allemagne|allemagne
987                                           berne|berne
991                   verlens|thurgovie|argovie|·|schwitz
998     constance|vevey|villars sous yens|vevey|neucha...
                              ...
6627                                                berne
6633                                lausanne|pully|neyruz
6639                                            vullerens
6640                                             lausanne
6649                                                    ·
Name: pensionnaires_origine, Length: 413, dtype: object

In [54]:
## save the filtered data to a new file located in the folder "pension"
df_pensionnaires.to_excel(filename.replace("filtered", "pension"))